[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc='0.8.19'
evm_version = 'shanghai'
bytecode_hash = 'none'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
gas_limit = 20000000



[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
scroll= "${RPC_SCROLL}"
celo = "${RPC_CELO}"
fantom_testnet = "${RPC_FANTOM_TESTNET}"
harmony = "${RPC_HARMONY}"
sepolia = "${RPC_SEPOLIA}"
mumbai = "${RPC_MUMBAI}"
bnb_testnet = "${RPC_BNB_TESTNET}"
bnb = "${RPC_BNB}"
gnosis = "${RPC_GNOSIS}"
base = "${RPC_BASE}"
plume="${RPC_PLUME}"
plume_mainnet="${RPC_PLUME_MAINNET}"
plume2="${RPC_PLUME_TEST2}"
plume3="${RPC_PLUME_TEST3}"
arb_sepolia="${RPC_ARBITRUM_SEPOLIA}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chainId=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chainId=43114}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chainId=137}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chainId=42161}
fantom={key="${ETHERSCAN_API_KEY_FANTOM}",chainId=250}
scroll={key="${ETHERSCAN_API_KEY_SCROLL}",chainId=534352, url='https://api.scrollscan.com/api\?'}
celo={key="${ETHERSCAN_API_KEY_CELO}",chainId=42220}
sepolia={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=11155111}
mumbai={key="${ETHERSCAN_API_KEY_MUMBAI}",chainId=11155111}
bnb_testnet={key="${ETHERSCAN_API_KEY_BNB}",chainId=97,url='https://api-testnet.bscscan.com/api'}
bnb={key="${ETHERSCAN_API_KEY_BNB}",chainId=56,url='https://api.bscscan.com/api'}
base={key="${ETHERSCAN_API_KEY_BASE}",chain=8453}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=100}
plume={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=161221135,url='https://plume-testnet.explorer.caldera.xyz'}
plume2={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=18230,url='https://www.oklink.com/plume-devnet'}
arb_sepolia={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=421614,url='https://sepolia.arbiscan.com'}
kinto_test={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=42888,url='https://plume-testnet.explorer.caldera.xyz'}
# See more config options https://github.com/gakonst/foundry/tree/master/config
